#  AUTHOR  :  lenindevops
#  project :  github-actions-cicd-pipeline

name: github actions cicd pipeline

on:
  push:
    branches: [ "main" ]
  
jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: compile the source code with maven
      run: mvn compile

  security-check:

    runs-on: ubuntu-latest
    needs:  compile

    steps:
    - uses: actions/checkout@v4
    - name: install the trivy
      run: |
        wget https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
        sudo dpkg -i trivy_0.18.3_Linux-64bit.deb
      
    - name: scan the filesystem using trivy
      run: trivy fs --format table -o fs-roport.json .
      
    - name: install gitleaks
      run: sudo apt install gitleaks -y
      
    - name: scan the filesystem using trivy
      run: gitleaks detect source . -r gitleaks-report.json -f json
      

    
